### ISSUE TITLE
需要作者一点帮助

### ISSUE THREAD

**Issue by eiriksgata** [zhantss/ffxiv-9card#1]
本人在写一个 FFXIV 九宫幻卡 NPC 对局模拟器 （web版） ，现阶段想要快速录入幻卡的数据，作者能提供一些格式化数据的帮助么？

**Comment by zhantss** [comment]
你需要哪方面的帮助？
我这个因为需要的是卡面数据和来源数据，主要是~~爬~~的
[最终幻想XIV中文维基](https://ff14.huijiwiki.com/wiki/%E4%B9%9D%E5%AE%AB%E5%B9%BB%E5%8D%A1%E5%8D%A1%E7%89%8C) 的卡牌和任务数据 
[ARR:Triple Triad 幻卡网站](https://arrtripletriad.com/cn/huan-ka-yi-lan)  相关NPC头像

你可以直接使用数据包文件下的卡牌相关数据
ffxiv-9card-assets
- ffxiv/icon 小图标 
- ffxiv/surface 卡面 
- assets/resources.xxxx.js 卡牌的json数据

~~目前6.3还没更新，爬虫程序不方便公开~~

如果只是需要结构化的对局数据考虑用FFCafe的中文解包数据，是csv文件
[卡牌库相关](https://github.com/thewakingsands/ffxiv-datamining-cn/blob/master/TripleTriadCard.csv)
[对局相关](https://github.com/thewakingsands/ffxiv-datamining-cn/blob/master/TripleTriadCardResident.csv)

如果你需要及时更新的话（国际服）
[解包](https://github.com/TexTools/FFXIV_TexTools_UI)，然后自行翻译

**Comment by eiriksgata** [comment]
> 你需要哪方面的帮助？ 我这个因为需要的是卡面数据和来源数据，主要是~爬~的 [最终幻想XIV中文维基](https://ff14.huijiwiki.com/wiki/%E4%B9%9D%E5%AE%AB%E5%B9%BB%E5%8D%A1%E5%8D%A1%E7%89%8C) 的卡牌和任务数据 [ARR:Triple Triad 幻卡网站](https://arrtripletriad.com/cn/huan-ka-yi-lan) 相关NPC头像
> 
> 你可以直接使用数据包文件下的卡牌相关数据 ffxiv-9card-assets
> 
> * ffxiv/icon 小图标
> * ffxiv/surface 卡面
> * assets/resources.xxxx.js 卡牌的json数据
> 
> ~目前6.3还没更新，爬虫程序不方便公开~
> 
> 如果只是需要结构化的对局数据考虑用FFCafe的中文解包数据，是csv文件 [卡牌库相关](https://github.com/thewakingsands/ffxiv-datamining-cn/blob/master/TripleTriadCard.csv) [对局相关](https://github.com/thewakingsands/ffxiv-datamining-cn/blob/master/TripleTriadCardResident.csv)
> 
> 如果你需要及时更新的话（国际服） [解包](https://github.com/TexTools/FFXIV_TexTools_UI)，然后自行翻译

感谢您的回复，我这边看了一下，目前会用到您项目下的 ffxiv-9card-record.json 数据 ，以及surface 和 icon 里面的图片。
后续的话可能会用到 每个NPC的卡组数据，不过这个收录不是着急。如果有其他方面的需求我再跟您说。我这个项目也是作为非盈利 的开源项目使用。

**Comment by zhantss** [comment]
> 感谢您的回复，我这边看了一下，目前会用到您项目下的 ffxiv-9card-record.json 数据 ，以及surface 和 icon 里面的图片。 后续的话可能会用到 每个NPC的卡组数据，不过这个收录不是着急。如果有其他方面的需求我再跟您说。我这个项目也是作为非盈利 的开源项目使用。

源文件的话你随便使用就行，NPC卡组数据这个我没~~爬~~，主要是目前这个用不到，你可以去ARR上面找，NPC的页面有这个数据
